config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :blogs
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :blog_categories
  has_many :categories, through: :blog_categories
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :body, presence: true, length: {minimum: 10, maximum: 300}

end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blog_categories
  has_many :blogs, through: :blog_categories
  validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum:25}
end

app/models/user.rb
class User < ApplicationRecord
  before_save{ self.email = email.downcase }
  has_many :blogs, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    # Verify email with ruby's standard library regex
                    format: {with: URI::MailTo::EMAIL_REGEXP}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # allows this method to be used as a helper method in our views
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [ :show, :edit, :update, :destroy ]
  before_action :require_user, except: [ :show, :index ]
  before_action :require_same_user, only: [ :edit, :update, :destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all.sort
    @blogs = Blog.paginate(page: params[:page], per_page: 5)

  end

  # GET /blogs/1 or /blogs/1.json
  def show

  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  def edit

  end


  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    if @blog.save #validation occurs if this fails
      flash[:notice] = "Blog was created successfully."
        redirect_to @blog
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    # binding.break

    if @blog.update(blog_params)
      flash[:notice] = "Blog updated succesfully"
      redirect_to @blog
    else
      render "edit"
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy

    @blog.destroy!
    redirect_to blogs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, category_ids: [])
    end
    def require_same_user
      if current_user != @blog.user
        flash[:alert] = "You can only edit or delete your own blog"
        redirect_to @blog
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created'
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category updated successfully"
      redirect_to @category
  else
    render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @blogs = @category.blogs.paginate(page: params[:page], per_page: 3)
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to blogs_path if logged_in?
  end
  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'

    end
  end
  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [ :edit, :update ]
  before_action :require_same_user, only: [ :edit, :update, :destroy ]



  def show
    @blogs = @user.blogs.paginate(page: params[:page], per_page: 3)

  end
  def new
    @user = User.new
  end
  def index
    @users = User.all.paginate(page: params[:page], per_page: 3)

  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was updated successfully"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Blog #{@user.username}, you have sucessfully signed up"
      redirect_to blogs_path
    else
      render 'new'
    end
  end

    def destroy
      @user.destroy
      session[:user_id] = nil
      flash[:notice] = "Account and all associated blogs have been deleted successfully"
      redirect_to root_path
    end
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def require_same_user
    if current_user != @user
      flash[:alert] = "You can only edit or delete your own profile"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 } )
  # get the email from URL-parameters or what have you and make lowercase
  email_address = user.email.downcase
  # create the md5 hash
  hash = Digest::MD5.hexdigest(email_address)
  size = options[:size]
  # compile URL which can be used in <img src="RIGHT_HERE"...
  gravatar_url = image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
  image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")

  end




end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_blog.html.erb
<div class="container">
    <% @blogs.each do |blog|%>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow-none mb-5 bg-light rounded">
          <div class="card-header font-italic">
            <% if blog.user %>
            By <%= link_to blog.user.username, user_path(blog.user) %>
            <% end %>
            <% if blog.categories.any? %>
              <div class="mt-2"> <%= render blog.categories %> </div>
            <% end %>
          </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to blog.title, blog_path(blog)%></h5>
              <p class="card-text"><%= truncate(blog.body, length: 100) %></p>
              <button type="button" class="btn btn-outline-dark"><%= link_to "Show", blog_path(blog)  %></button>
              <% if logged_in? && blog.user == current_user %>
                <button type="button" class="btn btn-outline-dark"><%= link_to "Edit", edit_blog_path(blog)  %></button>
                <button type="button" class="btn btn-outline-danger"><%= link_to "Delete", blog_path(blog), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?" } %>  </button>
              <% end %>
            </div>
            <div class="card-footer text-body-secondary">
              <small>Created <%= time_ago_in_words(blog.created_at)%> ago,
                edited <%=time_ago_in_words(blog.updated_at)%> ago</small>
            </div>
          </div>
        </div>
    <% end %>
</div>

app/views/blogs/_form.html.erb
    <div class= "row justify-content-center">
        <div class="col-10">
        <%= render 'shared/errors', obj: @blog %>

        <%= form_with(model: @blog, class: "shadow p-3 mb-3 bg-white rounded", data: {turbo: false}, local: true, ) do |f| %>
            <div class="form-group row">
            <%= f.label :title, class: "col-2 mb-3 col-form-label"%>
            <div class= "col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of blog" %>
            </div>
        </div>

        <div class="form-group row">
            <%= f.label :body, class: "col-2 col-form-label"%>
             <div class= "col-10">
            <%= f.text_area :body, rows:10, class: "form-control shadow rounded mb-3", placeholder: "Description of blog" %>
            </div>
        </div>
         <div class="form-group row">
            <%= f.label :category, class: "col-2 col-form-label"%>
             <div class= "col-10">
                <%= f.collection_select :category_ids, Category.all, :id, :name,{prompt: "Make your selection from the list below (can be empty)"}, {multiple: true, size: 3, class: "form-select shadow rounded mb-3"}  %>
            </div>
        </div>
        <div class="text-center">
            <%= f.submit class: "btn btn-outline-dark"%>
            </div>

    <%= link_to "[ Cancel and return to blogs listing ]", blogs_path%>
    <% end %> 
        </div>
        </div>

app/views/blogs/edit.html.erb
<div id="page-content">

  <h1 id= "show" class ="text-center">Edit blog</h1>
<%= render "form"%>
</div>

app/views/blogs/index.html.erb
  <h1 id= 'logo'class ="text-center">Blogs Listing Page</h1>
<div class="flickr_pagination">
    <%= will_paginate @blogs, :container => false %>
  </div>
  <%= render 'blog'%>

app/views/blogs/new.html.erb
  <h1 id= "show" class ="text-center">Create a new blog</h1>
<%= render "form"%>

app/views/blogs/show.html.erb
<h2 id= "show"class ="text-center"><%= @blog.title %></h2>
  <div class="container-fluid">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow-none mb-5 bg-light rounded">
          <div class="card-header font-italic">
            By <%= @blog.user.username if @blog.user%>
            <%= link_to gravatar_for(@blog.user), user_path(@blog.user)%>
            <% if @blog.categories.any? %>
              <div class="mt-2"> <%= render @blog.categories %> </div>
            <% end %>
          </div>
            <div class="card-body">
              <div class="card-text text-start"><%= simple_format(@blog.body) %></div>
              <% if logged_in? && @blog.user == current_user %>
              <button type="button" class="btn btn-outline-dark"><%= link_to "Edit", edit_blog_path(@blog)  %></button>
              <button type="button" class="btn btn-outline-danger"><%= link_to "Delete", blog_path(@blog), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?" } %>  </button>
              <% end %>
            </div>
            <div class="card-footer text-body-secondary">
              <small>Created <%= time_ago_in_words(@blog.created_at)%> ago,
                edited <%=time_ago_in_words(@blog.updated_at)%> ago</small>
            </div>
          </div>      

app/views/categories/_category.html.erb
<span class="badge rounded-pill bg-info text-dark"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
        <%= render 'shared/errors', obj: @category %>

        <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-white rounded", data: {turbo: false}, local: true, ) do |f| %>
            <div class="form-group row">
            <%= f.label :name, 'Category Name', class: "col-2 mb-3 col-form-label"%>
            <div class= "col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
            </div>
        </div>
        <div class="text-center">
            <%= f.submit class: "btn btn-outline-dark" %>
            </div>
                <%= link_to "[ Cancel and return to categories listing ]", categories_path(@category), class: "text-center"%>

            <% end %>

app/views/categories/edit.html.erb
<h1 id= "show" class ="text-center">Edit category name</h1>
<div class= "row justify-content-center">
       <%= render 'form'%>

    </div>
</div>

app/views/categories/index.html.erb
 <h1 id= 'logo'class ="text-center">Categories Listing Page</h1>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>
<div class="container">
    <% @categories.each do |category|%>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow-none mb-5 bg-light rounded">
            <div class="card-body">
              <h5 class="card-title"><%= link_to category.name, category_path(category)%></h5>
            <p class="card-text"><%= pluralize(category.blogs.count, "blog") %></p>
            </div>
            <div class="card-footer text-body-secondary">
              <small>Created <%= time_ago_in_words(category.created_at)%> ago,
                edited <%=time_ago_in_words(category.updated_at)%> ago</small>
            </div>
          </div>
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<h1 id= "show" class ="text-center">Create a new category</h1>
<div class= "row justify-content-center">
        <div class="col-10">
       <%= render 'form'%>
    </div>
</div>

app/views/categories/show.html.erb
<h1 id= "show" class ="text-center"><%= @category.name %> </h1>

<div class="text-center">
  <% if logged_in? && current_user.admin?%>
  <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-dark"%>
  <% end %>
 </div>
  <h3 id= "show" class ="text-center">Blogs</h3>

  <div class="flickr_pagination">
    <%= will_paginate @blogs, :container => false %>
  </div>

<%= render 'blogs/blog'%>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg|%>
      <div class="alert <%= (name =='notice')? "alert-success" : "alert-danger"%> alert-dismissible fade show" role="alert">
      <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</div>      

    <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand",id: "logo"%>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                <%= link_to "Bloggers", users_path, class:"nav-link"%>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Blogs
                    </a>
                    <ul class="dropdown-menu">
                        <% if logged_in? %>
                        <%= link_to "Create new blog", new_blog_path, class: "dropdown-item"%>
                        <% end %>
                        <%= link_to "View blogs", blogs_path, class: "dropdown-item"%>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Categories
                    </a>
                    <ul class="dropdown-menu">
                        <% if logged_in? && current_user.admin? %>
                        <%= link_to "Create new category", new_category_path, class: "dropdown-item"%>
                        <% end %>
                        <%= link_to "View categories", categories_path, class: "dropdown-item"%>
                    </ul>
                </li>
                
                <% if logged_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
                    </a>
                    <ul class="dropdown-menu">
                        <%= link_to "View your profile", user_path(current_user), class: "dropdown-item"%>
                        <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item"%>
                        <%= link_to "Delete Account", user_path(current_user), class: "dropdown-item text-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                    </ul>
                </li>
                
                <li class="nav-item">
                    <%= link_to "Logout", logout_path, class:"nav-link", data: {turbo_method: :delete} %>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to "Login", login_path, class:"nav-link"%>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign Up", signup_path, class:"nav-link"%>
                </li>
                <% end %>

            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
        <div id = 'page-content'>
      <%= render 'layouts/messages' %>
      <%= yield %>
      </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About Page</h1>

<%= link_to "Home Page", root_path%> | 
<%= link_to "Blogs Listing", blogs_path%>

app/views/pages/home.html.erb
<div class="container-fluid" id="home-container">
    <div class="jumbotron text-center">
        <h1 class="display-4">Welcome to the Blog.</h1>
        <p class="lead">What is your story? Come share it with us.</p>
        <hr class="my-4">
        <p>Make an account and start sharing</p>
        <p class="lead">
            <%= link_to "Sign Up!", signup_path, class: "btn btn-primary btn-lg"%>
        </p>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
<h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase%> from being saved</h4>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
<ul>
    <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
    <%end%>
 </ul>
</div>
<%end%>

app/views/users/_form.html.erb
<div class= "row justify-content-center">
        <div class="col-10">
        <%= render 'shared/errors', obj: @user %>

        <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-white rounded", data: {turbo: false}, local: true, ) do |f| %>
            <div class="form-group row">
            <%= f.label :username, class: "col-2 mb-3 col-form-label"%>
            <div class= "col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
            </div>
        </div>

        <div class="form-group row">
            <%= f.label :email, class: "col-2 col-form-label"%>
             <div class= "col-10">
            <%= f.email_field :email, class: "form-control shadow rounded mb-3", placeholder: "Enter your email address" %>
            </div>
        </div>

        <div class="form-group row">
            <%= f.label :password, class: "col-2 col-form-label"%>
             <div class= "col-10">
            <%= f.password_field :password, class: "form-control shadow rounded mb-3", placeholder: "Choose a password" %>
            </div>
        </div>

        <div class="text-center">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-dark") %>
            </div>

    <%= link_to "[ Cancel and return to blogs listing ]", blogs_path%>
    <% end %> 
        </div>
    </div>

app/views/users/edit.html.erb
  <h1 id= "show" class ="text-center">Edit your profile</h1>
<%= render "form"%>

app/views/users/index.html.erb
  <h1 id= "show" class ="text-center"> Alpha Bloggers </h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>

<div class="container">
    <% @users.each do |user|%>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow-none mb-5 bg-light rounded">
          <div class="card-header font-italic">
             <%= link_to user.username, user_path(user) %>
          </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user_path(user)%></h5>
              <p class="card-text"><%= pluralize(user.blogs.count, "blog") %></p>
              <button type="button" class="btn btn-outline-dark"><%= link_to "Show profile", user%></button>
              <% if logged_in? && user == current_user %>
              <button type="button" class="btn btn-outline-dark"><%= link_to "Edit profile", edit_user_path(user)  %></button>
              <% end %>
            </div>
            <div class="card-footer text-body-secondary">
              <small>Joined <%= time_ago_in_words(user.created_at)%> ago</small>
            </div>
          </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
  <h1 id= "show" class ="text-center">Sign up for an account</h1>
<%= render "form"%>

app/views/users/show.html.erb
  <h1 id= "show" class ="text-center"><%= @user.username%>'s profile </h1>
<%= gravatar_for @user, size: 200%>

<div class="text-center">
  <% if logged_in? && @user == current_user %>
  <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-dark"%>
  <% end %>
 </div>
  <h3 id= "show" class ="text-center">Blogs</h3>

  <div class="flickr_pagination">
    <%= will_paginate @blogs, :container => false %>
  </div>

<%= render 'blogs/blog'%>